[versions]
android-material = "1.12.0"
android-shell = "1.0.0"
android-snowfall = "1.2.1"
android-volley = "1.2.1"
androidx-appcompat = "1.7.0"
androidx-constraint = "2.2.0"
androidx-coordinator = "1.2.0"
androidx-core = "1.15.0"
androidx-leanback = "1.2.0-alpha04"
androidx-leanback-paging = "1.1.0-alpha11"
androidx-leanback-tab = "1.1.0-beta01"
androidx-localbroadcast = "1.1.0"
androidx-palette = "1.0.0"
androidx-preference = "1.2.1"
androidx-recyclerview = "1.3.2"
androidx-work = "2.10.0"
apl-appintro = "v4.2.3"
espresso-core = "3.6.1"
fastlane-screengrab = "2.1.1"
guardian-jtorctl = "0.4.5.7"
junit = "4.13.2"
junit-version = "1.2.1"
navigation-fragment-ktx = "2.8.5"
retrofit = "2.9.0"
rootbeer-lib = "0.1.0"
tor-android = "0.4.8.13.2"
pcap-core = "1.8.2"
pcap-factory = "1.8.2"

[libraries]
android-material = { group = "com.google.android.material", name = "material", version.ref = "android-material" }
android-shell = { group = "com.jaredrummler", name = "android-shell", version.ref = "android-shell" }
android-snowfall = { group = "com.github.jetradarmobile", name = "android-snowfall", version.ref = "android-snowfall" }
android-volley = { group = "com.android.volley", name = "volley", version.ref = "android-volley" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-constraint = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraint" }
androidx-coordinator = { group = "androidx.coordinatorlayout", name = "coordinatorlayout", version.ref = "androidx-coordinator" }
androidx-core = { group = "androidx.core", name = "core", version.ref = "androidx-core" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junit-version" }
androidx-leanback-core = { group = "androidx.leanback", name = "leanback", version.ref = "androidx-leanback" }
androidx-leanback-paging = { group = "androidx.leanback", name = "leanback-paging", version.ref = "androidx-leanback-paging" }
androidx-leanback-preferences = { group = "androidx.leanback", name = "leanback-preference", version.ref = "androidx-leanback" }
androidx-leanback-tab = { group = "androidx.leanback", name = "leanback-tab", version.ref = "androidx-leanback-tab" }
androidx-localbroadcast = { group = "androidx.localbroadcastmanager", name = "localbroadcastmanager", version.ref = "androidx-localbroadcast" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation-fragment-ktx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation-fragment-ktx" }
androidx-palette = { group = "androidx.palette", name = "palette", version.ref = "androidx-palette" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "androidx-preference" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidx-recyclerview" }
androidx-work = { group = "androidx.work", name = "work-runtime", version.ref = "androidx-work" }
androidx-work-kotlin = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidx-work" }
apl-appintro = { group = "com.github.apl-devs", name = "appintro", version.ref = "apl-appintro" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
fastlane-screengrab = { group = "tools.fastlane", name = "screengrab", version.ref = "fastlane-screengrab" }
guardian-jtorctl = { group = "info.guardianproject", name = "jtorctl", version.ref = "guardian-jtorctl" }
junit = { module = "junit:junit", version.ref = "junit" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
rootbeer-lib = { module = "com.scottyab:rootbeer-lib", version.ref = "rootbeer-lib" }
tor-android = { group = "info.guardianproject", name = "tor-android", version.ref = "tor-android" }
pcap-core = { group = "org.pcap4j", name = "pcap4j-core", version.ref = "pcap-core" }
pcap-factory = { group = "org.pcap4j", name = "pcap4j-packetfactory-static", version.ref = "pcap-factory" }
